### PR TITLE
add optional parameters to control SetTotalBytesLimit

### PR DESCRIPTION
**Pull request by andreasgal**

### CODE REVIEW

**Comment by fuwaneko** [comment]
Please, explain use cases for this.

**Comment by andreasgal** [comment]
I am parsing caffe models with node-protobuf, and they tend to be beyond the 60MB limit that Google's code has by default. I am sure this isn't the only real world use of huge protobufs out there. I didn't want to just up the default at compile time since Google's rationale for a limited default is sane (avoid DOS attacks).

See: https://groups.google.com/forum/#!topic/caffe-users/0b2bAngjbWc

**Comment by fuwaneko** [comment]
@andreasgal I don't think that protobuf messages above 1Mb are a good design decision, though I suspected that you're trying to use caffe since deep learning is a thing right now. Okay, while I still think raising that limit is dangerous, it's better to be able to do it manually if you know what you're doing. I'll accept PR as soon as I'm free.

**Comment by andreasgal** [comment]
I completely agree with you. Caffe's use of protobuf messages is a terrible, terrible, design, but its what it is.

**Pull request merged**
